-- Realtime Guestbook MVP schema
-- Run this in the Supabase SQL editor.
--
-- The app uses the existing public.guestbook table for posts. If the table
-- already exists with only id, created_at, and content, the ALTER statements
-- below add the columns needed for author names, image uploads, and post-it
-- rendering.

create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  content text not null default ''
);

alter table public.guestbook
  add column if not exists author_name text,
  add column if not exists image_url text,
  add column if not exists image_type text,
  add column if not exists rotation numeric not null default 0;

alter table public.guestbook
  alter column content set default '',
  alter column rotation set default 0;

update public.guestbook
set author_name = '익명'
where author_name is null or char_length(trim(author_name)) = 0;

alter table public.guestbook
  alter column author_name set not null;

alter table public.guestbook
  drop constraint if exists guestbook_author_name_check,
  add constraint guestbook_author_name_check
    check (char_length(trim(author_name)) > 0),
  drop constraint if exists guestbook_content_or_image_check,
  add constraint guestbook_content_or_image_check
    check (char_length(trim(coalesce(content, ''))) > 0 or image_url is not null),
  drop constraint if exists guestbook_image_type_check,
  add constraint guestbook_image_type_check
    check (image_type is null or image_type in ('photo', 'drawing'));

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.guestbook(id) on delete cascade,
  author_name text,
  content text,
  created_at timestamptz not null default now()
);

alter table public.comments
  add column if not exists post_id bigint references public.guestbook(id) on delete cascade,
  add column if not exists author_name text,
  add column if not exists content text,
  add column if not exists created_at timestamptz not null default now();

alter table public.comments
  alter column content set default '';

update public.comments
set author_name = '익명'
where author_name is null or char_length(trim(author_name)) = 0;

update public.comments
set content = ''
where content is null;

alter table public.comments
  alter column author_name set not null,
  alter column content set not null,
  alter column post_id set not null;

alter table public.comments
  drop constraint if exists comments_author_name_check,
  add constraint comments_author_name_check
    check (char_length(trim(author_name)) > 0),
  drop constraint if exists comments_content_check,
  add constraint comments_content_check
    check (char_length(trim(content)) > 0);

create index if not exists guestbook_created_at_idx
  on public.guestbook (created_at desc);

create index if not exists comments_post_id_created_at_idx
  on public.comments (post_id, created_at asc);

alter table public.guestbook enable row level security;
alter table public.comments enable row level security;

drop policy if exists "Anyone can read guestbook posts" on public.guestbook;
create policy "Anyone can read guestbook posts"
  on public.guestbook for select
  using (true);

drop policy if exists "Anyone can create guestbook posts" on public.guestbook;
create policy "Anyone can create guestbook posts"
  on public.guestbook for insert
  with check (
    char_length(trim(author_name)) > 0
    and (
      char_length(trim(coalesce(content, ''))) > 0
      or image_url is not null
    )
    and (image_type is null or image_type in ('photo', 'drawing'))
  );

drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments"
  on public.comments for select
  using (true);

drop policy if exists "Anyone can create comments" on public.comments;
create policy "Anyone can create comments"
  on public.comments for insert
  with check (
    char_length(trim(author_name)) > 0
    and char_length(trim(content)) > 0
  );

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'guestbook'
  ) then
    execute 'alter publication supabase_realtime add table public.guestbook';
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'comments'
  ) then
    execute 'alter publication supabase_realtime add table public.comments';
  end if;
end $$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'guestbook-media',
  'guestbook-media',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Anyone can upload guestbook media" on storage.objects;
create policy "Anyone can upload guestbook media"
  on storage.objects for insert
  to anon
  with check (
    bucket_id = 'guestbook-media'
    and (storage.foldername(name))[1] = 'posts'
  );

drop policy if exists "Anyone can read guestbook media" on storage.objects;
create policy "Anyone can read guestbook media"
  on storage.objects for select
  to anon
  using (
    bucket_id = 'guestbook-media'
    and (storage.foldername(name))[1] = 'posts'
  );
